name: flutter_spark
description: A Simple CLI to generate folder architecture for your flutter project.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  args: ^2.5.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.20.2
  analyzer: ^6.4.1 

executables:
  spark: architecture